title: Did the Tampa Bay Buccaneers Win?
email: hello@didbucswin.com
author: Brian OToole
description: #
baseurl: "" # the subpath of your site, e.g. /blog
current_team: Buccaneers
url: http://didbucswin.com # the base hostname & protocol for your site, e.g. http://example.com
url_jags: http://didjagswin.com
url_browns: http://didbrownswin.com
url_bucs: http://didbucswin.com
url_dolphins: http://didphinswin.com
twitter_username: brianotoole
github_username:  brianotoole

# Build settings
markdown: kramdown
#theme: minima

sass:
  compressed: true
  
gems:
  #- jekyll-feed
 
# Files in this repo that we don't want to go to the web 
exclude: [
  'scss',
  '*.rb',
  '*.yml', 
  'vendor', 
  'Gemfile', 
  'Gemfile.lock',
  '*.sh',
  'README.md',
  'LICENSE.md',
]